[versions]
androidGradlePlugin = '7.0.4'
kotlin = '1.6.0'
kotlinCoroutines = '1.6.0-native-mt'
ktor = '1.6.7'

kitPresentationRedux = '1.3.1'

androidCompose = '1.1.0-rc01'

[libraries]
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlinSerialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version = "10.2.0" }
plugin-gradleVersionUpdates = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.39.0" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }

kit-model = { module = "ru.nobird.app.core:model", version = "1.0.8" }
kit-presentation-redux = { module = "ru.nobird.app.presentation:presentation-redux", version.ref = "kitPresentationRedux" }
kit-presentation-reduxCoroutines = { module = "ru.nobird.app.presentation:presentation-redux-coroutines", version.ref = "kitPresentationRedux" }

android-ui-material = { module = "com.google.android.material:material", version = "1.4.0" }
android-ui-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.0" }
android-ui-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.2" }

android-compose-activity = { module = "androidx.activity:activity-compose", version = "1.4.0" }
android-compose-material = { module = "androidx.compose.material:material", version.ref = "androidCompose" }
android-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "androidCompose" }
android-compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidCompose" }
#android-compose-themeAdapter = { module = "com.google.android.material:compose-theme-adapter", version.ref = "androidCompose" }
android-compose-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.4.0" }
android-compose-coil = { module = "io.coil-kt:coil-compose", version = "2.0.0-rc01" }

android-test-junit = { module = "junit:junit", version = "4.13.2" }
android-test-runner = { module = "androidx.test:runner", version = "1.4.0" }
android-test-robolectric = { module = "org.robolectric:robolectric", version = "4.7.1" }

[bundles]
ktor-common = ['ktor-core', 'ktor-serialization', 'ktor-logging']
android-test = ['android-test-junit', 'android-test-runner', 'android-test-robolectric']
android-compose = [
    'android-compose-activity', 'android-compose-material', 'android-compose-animation',
    'android-compose-tooling',
#    'android-compose-themeAdapter',
    'android-compose-viewmodel',
    'android-compose-coil'
]